### ISSUE TITLE
MotionCollector & Camera

### ISSUE THREAD

**Issue by pmd2245** [degtiarev/MotionCollector#1]
Hi @degtiarev ,

First of all, thanks for sharing your work. I tried your app and it works perfectly. 
Do you think it is possible to integrate the camera in the sensor acquisition loop?

Thanks in advance,
Pm

**Comment by degtiarev** [comment]
Hi @pmd2245 ,

I'm glad to hear that my app helped somebody. 
There should be no problem. I suppose it would be better to store photos as files in /Documents inside the app and photo_id in Core Data. To export data, you need to archive all pictures into one archive-file (to not to export by hands a lot of generated files).

**Comment by pmd2245** [comment]
@degtiarev, many thanks for your reactivity and your advices .

To be honest, I am not very familiar with oriented object programming. I would really appreciate if you could provide me some references about the camera stuff.

**Comment by degtiarev** [comment]
https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/
https://hackernoon.com/swift-access-ios-camera-and-photo-library-dc1dbe0cdd76
