### ISSUE TITLE
How stable the data recording is for Apple Watch?

### ISSUE THREAD

**Issue by YinghaoHuang91** [degtiarev/MotionCollector#2]
Thanks for making this project public! It's really a great source of tutorial to me for reference. And I wonder how stable the data recording is for Apple Watch? Based on my experience, sometimes a lot of sensor readings can be lost for consumer-level IMUs, not to mention a stable frame rate. I would like to buy one Apple Watch myself to give it a try if it yields stable sensor readings.

**Comment by geekfeiw** [comment]
@YinghaoHuang91 
Hi, Have you tried?

**Comment by YinghaoHuang91** [comment]
@geekfeiw Sorry for the late response. It's been a long time and my memory is not fresh and accurate anymore. I think the frame rate is not very stable, but still acceptable. Of course it's highly dependent upon what your use case is.
