### ISSUE TITLE
lovely work.

### ISSUE THREAD

**Issue by GINNOV** [degtiarev/MotionCollector#4]
Thank you for sharing your work. It is nicely put together and quite useful. Have you considered adding realtime (in chunks) sharing with the phone when recording from the watch?

**Comment by degtiarev** [comment]
Hi. It should work. If you set switcher on "Record data from phone" on watch and start the process of recording from the watch, it'll record data from both: watch and phone.

**Comment by GINNOV** [comment]
thank you after messing a bit with it, I found the sequence and timing that made it work. Thanks again for sharing your work!
