### ISSUE TITLE
WatchKit 1.0 apps are no longer installable on this watchOS version.

### ISSUE THREAD

**Issue by geekfeiw** [degtiarev/MotionCollector#6]
Hi @degtiarev 

I am going to build MotionCollectorWatch to the simulator of apple watch 5series 40nm.
It shows the following issue. Could you please tell me how can I fix this?

Details

This app could not be installed at this time.
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.

Recovery Suggestion: WatchKit 1.0 apps are no longer installable on this watchOS version.
--
WatchKit 1.0 apps are no longer installable on this watchOS version.
Domain: MIInstallerErrorDomain
Code: 133
User Info: {
    FunctionName = "-[MIInstallableBundle _isValidWatchKitApp:withVersion:installableSigningInfo:error:]";
    LegacyErrorString = UnsupportedWatchKitVersion;
    SourceFileLine = 698;
}
--

System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 12.1 (17222)

**Comment by degtiarev** [comment]
Hi,

I currently don’t have Apple Watch to look at it. Try [this](https://developer.apple.com/forums/thread/660784) solution
